### ISSUE TITLE
Opting out of the "master" to "main" change?

### ISSUE THREAD

**Issue by outloudvi** [suisei-cn/code-of-conduct#2]
As per https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/, the default branch of new repositories will be "main" from Oct 1. We may opt out of this by manually change it in https://github.com/organizations/suisei-cn/settings/repository-defaults, so will we do this?

**Comment by OriginCode** [comment]
**NOPE**
**KEEP MASTER, AND EVEN SLAVE**

**Comment by outloudvi** [comment]
~@OriginCode may I see your words as if you are in support of not making manual changes and let GitHub change the default branch name to "main"?~

Oh I got it.

**Comment by outloudvi** [comment]
Closed. According to the consensus (most people are for this opt-out or do not care), `suisei-cn` is opting out of the change.
